version: '3.3'
services:
    orain:
        image: oraichain/oraius-oraichain-pro:0.0.1
        working_dir: /root
        tty: true
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        ports:
            - 1317:1317
            - 26656:26656
            - 26657:26657
            - 9090:9090
            - 8545:8545
        cap_add:
            - SYS_PTRACE
        environment:
            - CHAIN_ID=oraichainpro_66666-1
            - NODE_NAME=fullnode
            - DATA_HOME=/root/.evmosd
            - PERSISTENT_PEERS=4725ef9ef94b4a23fcf99b62b2729ad029545c68@159.203.165.199:26656
        volumes:
            - ./init.sh:/root/init.sh
            - ./.evmosd:/root/.evmosd
            - cosmovisor:/root/cosmovisor
        command: sh init.sh

volumes:
    cosmovisor: null
