version: '3.3'
services:
    orain:
        image: orai/orai-balcony:0.0.1
        working_dir: /root
        tty: true
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        ports:
            - 1317:1317
            - 26656:26656
            - 26657:26657
            - 9090:9090
            - 8545:8545
        cap_add:
            - SYS_PTRACE
        environment:
            - NODE_NAME=fullnode
            - DATA_HOME=/root/.evmosd
        volumes:
            - ./init.sh:/root/init.sh
            - ./.evmosd:/root/.evmosd
        command: sh init.sh
